### ISSUE TITLE
Problem with x-kinvey-client-app-version header

### ISSUE THREAD

**Issue by egkozlov** [Kinvey/business-logic-testing-library#3]
@amoothart I'm trying to add "x-kinvey-client-app-version" header to my request object, but when I add it I always get an error.
There is code that I use to create request object:

``` javascript
var requestObject = tester.createMockRequest();
        requestObject.addHeader('x-kinvey-api-version', 3);
        requestObject.addHeader('x-kinvey-client-app-version', 2);
        requestObject.setAuthenticatedUsername('testUser2');
```

Here is the stacktrace:

```
 done() invoked with non-Error: {"isError":true,"statusCode":550,
"error":"TypeError: Object 2 has no method 'split'","message":"Internal Error","debugMessage":"Unable to compile business logic script - missing arguments",
"stackTrace":"TypeError: Object 2 has no method 'split'\n  at /opt/kinvey/business-logic-runner/node_modules/business-logic-api/lib/modules/requestContext.js:13:26\n 
 at /opt/kinvey/business-logic-runner/node_modules/business-logic-api/lib/modules/requestContext.js:38:9\n
  at module.exports.generate (/opt/kinvey/business-logic-runner/node_modules/business-logic-api/lib/api.js:188:27)\n  
at Object.module.exports.getApi (/opt/kinvey/business-logic-runner/node_modules/business-logic-api/lib/api.js:266:16)\n 
 at exports.build (/opt/kinvey/business-logic-runner/lib/buildScript.js:39:17)\n
  at processBL (/opt/kinvey/business-logic-runner/lib/runner.js:160:18)\n  
at processTasks (/opt/kinvey/business-logic-runner/lib/runner.js:221:22)\n  at Socket.<anonymous> (/opt/kinvey/business-logic-runner/lib/runner.js:252:18)\n  
at Socket.emit (events.js:95:17)\n  at Socket.<anonymous> (_stream_readable.js:765:14)\n  
at Socket.emit (events.js:92:17)\n  at emitReadable_ (_stream_readable.js:427:10)\n  at emitReadable (_stream_readable.js:423:5)\n 
 at readableAddChunk (_stream_readable.js:166:9)\n  at Socket.Readable.push (_stream_readable.js:128:10)\n 
 at TCP.onread (net.js:529:21)\n","metadata":{},"rusage":{"utime":0,"stime":0,"maxrss":0,"ixrss":0,"idrss":0,"isrss":0,"minflt":0,"majflt":0,"nswap":0,"inblock":0,"oublock":0,"msgsnd":0,"msgrcv":0,"nsignals":0,"nvcsw":0,"nivcsw":0,"wtime":0.003000020980834961}}
    at test/business-logic/collections/Pet/onPreFetch.js:71:13
    at node_modules/kinvey-business-logic-testing-library/lib/tester.coffee:135:24
    at Socket.<anonymous> (node_modules/kinvey-business-logic-testing-library/lib/tester.coffee:54:16)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)

```

**Comment by galniv** [comment]
Passing the value of the header as the string `’2’` rather than the number `2` should do the trick.

**Comment by egkozlov** [comment]
Thanks @galniv! It solves the problem
