### ISSUE TITLE
Running tests twice return different results

### ISSUE THREAD

**Issue by cmolina** [Kinvey/business-logic-testing-library#6]
By running a simple test for a "hello world" endpoint produces different results every time the test in run.
### Errors

``` bash
$ ./node_modules/mocha/bin/mocha test/ --recursive

  take-medicine
    1) should return an array.

  0 passing (213ms)
  1 failing

  1) take-medicine should return an array.:

      Uncaught AssertionError: expected 200 to equal 201
      + expected - actual

      -200
      +201

    at test/business-logic/endpoints/take-medicine.js:34:38
    at node_modules/kinvey-business-logic-testing-library/lib/tester.coffee:139:5
    at Socket.<anonymous> (node_modules/kinvey-business-logic-testing-library/lib/tester.coffee:56:7)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Socket.Readable.push (_stream_readable.js:128:10)
    at TCP.onread (net.js:529:21)

$ ./node_modules/mocha/bin/mocha test/ --recursive

  take-medicine
    1) should return an array.

  0 passing (202ms)
  1 failing

  1) take-medicine should return an array.:
     SyntaxError: Could not parse JSON response. Unexpected end of input
    at Object.parse (native)
    at Socket.<anonymous> (node_modules/kinvey-business-logic-testing-library/lib/tester.coffee:42:27)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Socket.Readable.push (_stream_readable.js:128:10)
    at TCP.onread (net.js:529:21)
```
### Endpoint

``` javascript
function onRequest(request, response, modules) {
  response.body = { "hello": "world" };
  return response.complete(200);
}
```
### Test

``` javascript
// Test suite.
describe.only('take-medicine', function() {
  // Set the endpoint under test.
  before('configure', function() {
    this.endpoint = 'take-medicine';
  });

  before('populate', function(cb) {
    var data = require('../data/medicines-logs.json');
    this.client.dataStore.importCollectionData(
      'medicines-logs', data, true, cb);
  });

  after('configure', function() {
    delete this.endpoint; // Cleanup.
  });

  // Tests.
  it('should return an array.', function(done) {
    // Configure the request.
    var requestObject = {
      body: { }
    };

    // Run the endpoint.
    this.client.runCustomEndpoint(this.endpoint, requestObject, { }, function(err, blResult) {
      if (err) {
        return done(err);
      }
      var response = blResult.response;
      expect(response.statusCode).to.equal(201);
      //expect(response.body).to.have.property('length');
      done();
    });
  });
});
```

I am using node v0.10.14 (also tried with v4), Docker v1.10.3 build 20f81dd, in Ubuntu 15.10.

**Comment by cmolina** [comment]
A workaround is to stop the running containers, but after a while it fails again.

``` bash
$ docker stop $(docker ps -a -q)
$ docker rm $(docker ps -a -q)
```
